### ISSUE TITLE
Illegal Instruction on linux on top BBL

### ISSUE THREAD

**Issue by johnnavaj** [riscv/riscv-pk#193]
I have built the mainline linux and passed it as a payload to BBL . Using minimal initramfs as filesystem. 

I am getting a illegal instruction once i drop into the userspace , what could be the cause of this trap ?
 
Log as below 

![image](https://user-images.githubusercontent.com/31366212/77689059-1170c680-6fc7-11ea-9fd9-cee8fd3cf2a2.png)

**Comment by sahajgarg** [comment]
What emulator/simulator are you using? 
If you are using TinyEMU, try removing COUNTEREN_MASK from riscv_cpu.c. This disables many counters in user mode (bbl in riscv-pk appears to allow all counters in machine mode, regardless of whether the counters are disabled, which is why the issue only appears for user mode).

**Comment by sahajgarg** [comment]
The badaddr field (mtval) contains the faulting instruction, which appears to be a read to the CSR 0x105, which corresponds to stvec. This is supervisor read/write privilege, so that might be causing the illegal instruction.
